# Deprecated: Use one of the below markers instead, depending on the specific use case.
import pytest

PYTEST_INTEGRATION_MARKER = pytest.mark.integration

PYTEST_SLOW_MARKER = pytest.mark.slow
PYTEST_NONDETERMINISTIC_MARKER = pytest.mark.nondeterministic
PYTEST_DEPENDENT_MARKER = pytest.mark.dependent
PYTEST_EXPENSIVE_MARKER = pytest.mark.expensive
PYTEST_MANUAL_MARKER = pytest.mark.manual

PYTEST_THIRD_PARTY_API_MARKERS = [
    PYTEST_SLOW_MARKER,
    PYTEST_NONDETERMINISTIC_MARKER,
    PYTEST_DEPENDENT_MARKER,
]

PYTEST_MANUAL_MARKERS = [
    PYTEST_SLOW_MARKER,
    PYTEST_NONDETERMINISTIC_MARKER,
    PYTEST_DEPENDENT_MARKER,
    PYTEST_MANUAL_MARKER,
]

PYTEST_INTEGRATION_TEST_MARKERS = [
    PYTEST_INTEGRATION_MARKER,
    PYTEST_SLOW_MARKER,
    PYTEST_NONDETERMINISTIC_MARKER,
    PYTEST_DEPENDENT_MARKER,
    PYTEST_EXPENSIVE_MARKER,
    PYTEST_MANUAL_MARKER,
]
